# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTRWESulmew9XhKqGnZ2Bysp5TVivLVm
"""

import torch
print(torch.__version__, torch.cuda.is_available())

import torch
from torch.utils.data import DataLoader, random_split
from torchvision import datasets
from torchvision.datasets import OxfordIIITPet
from torchvision import transforms

import torch.nn as nn

class MyNet(nn.Module):
    def __init__(self, num_classes=37):
        super().__init__()
        self.features = nn.Sequential(
            #CNN 1
            nn.Conv2d(3, 16, kernel_size=3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(2),

            #CNN 2
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            #CNN 3
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            #CNN 4
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2),

            #CNN 5
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        logits = self.head(x)
        return logits  # return raw logits

#determine the contraints for the image to be calculated
IMG_SIZE = 128

train_tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.RandomResizedCrop(IMG_SIZE, scale=(0.8, 1.0)),
    transforms.ToTensor(),
])

test_tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
])

test_set = datasets.OxfordIIITPet(root="data", split="test",
                                  target_types="category",
                                  transform=test_tf, download=True)

# target_types="category" gives the 37-breed label
full_trainval = datasets.OxfordIIITPet(root="data", split="trainval",
                              target_types="category",
                              transform=train_tf, download=True)



print(full_trainval)  # expect 3680 items (37 breeds x ~100 each)

# Carve a validation set off trainval (test stays sealed)
val_size = int(0.2 * len(full_trainval))
train_size = len(full_trainval) - val_size
train_set, val_set = random_split(full_trainval, [train_size, val_size])

train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_set, batch_size=32)
test_loader = DataLoader(test_set, batch_size=32)


# Sanity check: pull one batch and look at the shape
images, labels = next(iter(train_loader))
print("batch shape:", images.shape)   # expect [32, 3, 64, 64]
print("labels:", labels[:8])
print("num classes:", len(full_trainval.classes))  # expect 37

import torch.nn as nn
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Training on device:", device)

#if os.path.exists("model.pth"):
#    model.load_state_dict(torch.load("model.pth", weights_only=True))
#    print("Loaded saved model weights.")
#else:
#    print("No saved model found — using a fresh, untrained model.")
model = MyNet().to(device)
print(model)

# calculate loss for multiclass
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)

def train_one_epoch(model, loader):
    # enable training mode to prevent complications with batchnorm
    model.train()
    running_loss = 0.0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        logits = model(images)
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    return running_loss / len(loader)

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        logits = model(images)
        preds = logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)
    return correct / total

EPOCHS = 30

for epoch in range(EPOCHS):
    train_loss = train_one_epoch(model, train_loader)
    val_acc = evaluate(model, val_loader)
    print(f"epoch {epoch+1:2d} | train loss {train_loss:.3f} | val acc {val_acc:.3f}")

test_acc = evaluate(model, test_loader)
train_acc = evaluate(model, train_loader)
print(f"FINAL  train acc {train_acc:.3f} | test acc {test_acc:.3f}")
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")